ItemManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('administracion/', include('administracion.urls')),
    path('desarrollo/', include('desarrollo.urls')),
    path('configuracion/', include('configuracion.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

administracion/urls.py
from django.urls import path

from administracion import views

app_name = 'administracion'
urlpatterns = [

    # URL DE PAO
    path('proyectos/<int:id_proyecto>/roles/crear/', views.crear_rol, name='crearRol'),
    path('proyectos/<int:id_proyecto>/roles', views.administrar_roles, name='administrarRoles'),
    path('proyectos/<int:id_proyecto>/roles/<int:id_rol>/desactivar/', views.desactivar_rol_proyecto, name='desactivarRol'),
    path('proyectos/<int:id_proyecto>/usuario/<int:id_usuario>/roles', views.ver_roles_usuario, name='verRolesUsuario'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>/roles/<int:id_rol>', views.desasignar_rol_al_usuario, name='desasignarRol'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>', views.asignar_rol_por_fase, name='asignarRol'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>/rol/<int:id_rol>', views.registrar_rol_por_fase, name='registrarRolPorFase'),
    # URLs DE MATI
    path('proyectos/<str:filtro>', views.proyectos, name='proyectos'),
    path('proyectos/crear/', views.crear_proyecto, name='crearProyecto'),
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    path('proyectos/<int:id_proyecto>/participantes', views.administrar_participantes, name='administrarParticipantes'),
    path('proyectos/<int:id_proyecto>/editar', views.editar_proyecto, name='editarProyecto'),
    path('proyectos/<int:id_proyecto>/estado', views.estado_proyectov2, name='estadoProyecto'),
    path('proyectos/<int:id_proyecto>/estado/<str:estado>', views.estado_proyectov2, name='estadoProyecto2'),
    path('proyectos/<int:id_proyecto>/adminfases', views.administrar_fases_del_proyecto, name='administrarFasesProyecto'),
    path('proyectos/<int:id_proyecto>/comite', views.administrar_comite, name='administrarComite'),
    path('proyectos/<int:id_proyecto>/<int:id_usuario>/<str:caso>', views.eliminar_participante_y_comite, name='desasignarUsuario'),
    path('proyectos/<int:id_proyecto>/accesodenegado/<str:caso>', views.acceso_denegado, name='accesoDenegado'),
    path('proyectos/<int:id_proyecto>/auditoria/<str:tipo>/', views.auditoria_particular, name='auditoriaParticular'),
    # URLs de DAVID
    path('tipo/todos', views.mostrar_tipo_item, name='tipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/showForImport', views.mostrar_tipo_import, name='importarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/mostrarImport', views.confirmar_tipo_import, name='confirmarImportarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/import', views.importar_tipo, name='importarTipoItemAProyecto'),
    path('proyectos/<int:id_proyecto>/tipo/', views.ver_tipo_por_proyecto, name='tipoItemPorProyecto'),
    path('proyectos/<int:id_proyecto>/tipo/crear/', views.crear_tipo, name='crearTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/editar/', views.editar_tipo, name='editarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/desactivar/', views.desactivar_tipo_item, name='desactivarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/registrarEnBase', views.registrar_tipoitem_en_base, name='registrarEnBase'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>', views.ver_tipo, name='verTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/atributo/crear', views.crear_atributo, name='crearAtributo'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/atributo/<int:id_atributo>/quitar/', views.quitar_atributo, name='quitarAtributo'),
]

configuracion/urls.py
from django.urls import path

from configuracion import views

app_name = 'configuracion'
urlpatterns = [
    # URLs de Mati
    path('<str:filtro>', views.index, name='indexConfiguracion'),
    path('proyectos/<int:id_proyecto>/item/<int:id_item>/trazabilidad', views.trazabilidad, name='trazabilidad'),
    path('proyectos/<int:id_proyecto>/item/<int:id_item>/trazabilidad/reporte', views.reporte_trazabilidad, name='reporteTrazabilidad'),

    # URLs de David
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    path('proyectos/fase/<int:id_fase>/crearLB', views.crear_linea_base, name='crearLineaBase'),
    path('proyectos/fase/lineabase/<int:id_lineabase>', views.ver_linea_base, name='verLineaBase'),
    path('proyectos/<int:id_proyecto>/comite/', views.comite_index, name='verIndexComite'),
    path('proyectos/<int:id_proyecto>/comite/<int:id_solicitud>/votar/<int:voto>', views.votar_solicitud, name='votarSolicitud'),
    path('proyectos/<int:id_proyecto>/cerrar', views.cerrar_proyecto, name='cerrarProyecto'),
    # URLs de Fer
    path('lineabase/<int:id_lineabase>', views.solicitud_ruptura, name='solicitudRuptura'),
    path('proyectos/<int:id_proyecto>/reporte', views.reporte, name='reporte'),

    # URLs de Pao
    path('proyectos/<int:id_proyecto>/item/<int:id_item>/solicitarDesaprobar', views.solicitud_modificacion_estado, name='solicitarModificarEstado'),
    #path('proyectos/<int:id_proyecto>/comite/<int:id_solicitud>/votarItem/<int:voto>', views.votar_solicitud_desaprobacion, name='votarSolicitudDesaprobacion')

]

desarrollo/urls.py
from django.urls import path

from desarrollo import views

app_name = 'desarrollo'
urlpatterns = [
    # URLs de Mati
    path('fase/<int:id_fase>/tipo/<int:id_tipo>/items/crear', views.crear_item, name='crearItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>', views.ver_item, name='verItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/historialversiones', views.historial_versiones_item,
         name='histVersionesItem'),
    path('proyectos/<int:id_proyecto>/aprobacion', views.menu_aprobacion, name='menuAprobacion'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/reversionar/<int:id_version_anterior>', views.reversionar_item,
         name='reversionarItem'),
    # path('items/<int:id_item>/calculo_impacto', views.calculo_de_impacto, name='calculoDeImpacto'),
    # URLs de David
    path('<str:filtro>', views.index, name='indexDesarrollo'),
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    # URLs de Fer
    path('proyectos/<int:id_proyecto>/relacionar', views.relacionar_item, name='relacionar'),
    path('proyectos/<int:id_proyecto>/desactivar_relacion', views.desactivar_relacion_item, name='desactivarRelacion'),
    path('proyectos/<int:id_proyecto>/cerrar_fase', views.cerrar_fase, name='cerrarFase'),
    # URLs de Pao
    path('items/<int:id_item>/solicitar', views.solicitud_aprobacion, name='solicitarAprobacion'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/desactivar', views.desactivar_item, name='desactivarItem'),
    path('items/<int:id_item>/aprobar', views.aprobar_item, name='aprobarItem'),
    path('items/<int:id_item>/desaprobar', views.desaprobar_item, name='desaprobarItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/editar', views.modificar_item, name='editarItem'),
    path('items/<int:id_item>/votar', views.votacion_item_en_revision_desarrollo, name='votacionItem'),
    path('items/<int:id_item>/votar2', views.votacion_item_en_revision_aprobado, name='votacionItem2'),
    path('items/<int:id_item>/votar3', views.votacion_item_en_revision_lineaBase, name='votacionItem3')
]

login/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.user_register, name='register'),

    path('admin/', views.admin, name='admin'),
    path('admin/access/', views.users_access, name='administrarAccesos'),
    path('<str:name>/update/', views.user_update, name='userUpdate'),
    path(
        'accesoDenegado/',
        TemplateView.as_view(template_name='login/accesoDenegado.html'),
        name='AccesoDenegado',
    ),

    # urls de Mati
    path('auditoria/<str:tipo>', views.auditoria, name='auditoria'),
]

login/views.py
"""
Modulo se detalla la logica para las vistas que serán utilizadas por la app
"""
# Django
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import auth

# Forms
from administracion.models import Proyecto, TipoItem, Fase, Rol, HistoricalParticipante
from configuracion.models import LineaBase
from desarrollo.models import HistoricalItem
from login.forms import RegisterForm, UpdateUserForm

# Models
from login.models import Usuario, HistoricalAccesos


@login_required
def index(request):
    """
    Método que muestra el index, validando antes si el usuario inició sesión

    :param request: objeto tipo diccionario que permite acceder a datos
    :return: objeto que se encarga de renderar admin.html, index.html o no_active.html
    :rtype: render
    """
    if request.user.is_superuser:
        return render(request, 'login/admin.html')
    elif request.user.is_active:
        return render(request, 'login/index.html')
    else:
        return render(request, 'login/no_active.html')


def user_login(request):
    """
    Vista que se encarga de loguear al usuario

    :param request: objeto tipo diccionario que permite acceder a datos
    :return: objeto que se encarga de renderar login.html
    :return: redirección a la vista index
    :rtype: render, redirect
    """

    if request.method == 'POST':

        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is None:
            message = 'Credenciales invalidas'
            return render(request, 'login/login.html', {'error_message': message})
        login(request, user)
        # request.session.set_expiry(3600)
        # SE SACA EL SESSION TIMEOUT DE CADA USUSARIO

        # registramos para auditoría
        audit = HistoricalAccesos(history_user=request.user, history_type=HistoricalAccesos.TIPO_ACCESO)
        audit.save()

        return redirect('login:index')

    return render(request, 'login/login.html')


def logout(request):
    """
    Función que se encarga de cerrar la sesión del usuario

    :param request: objeto tipo diccionario que permite acceder a datos
    :return: redireccion a la vista login
    :rtype: redirect
    """

    # primero registramos para auditoría
    audit = HistoricalAccesos(history_user=request.user, history_type=HistoricalAccesos.TIPO_SALIDA)
    audit.save()

    auth.logout(request)

    return redirect('login:login')


def admin(request):
    """
    Vista que solo sera visible para el administrador

    :param request: objeto tipo diccionario que permite acceder a datos
    :return: objeto que se encarga de renderar admin.html
    :rtype: render
    """
    return render(request, 'login/admin.html')


def users_access(request):
    """
    Vista para modificar el acceso de los usuarios al sistema, ademas hacer a un
    usuario gerente

    :param request: objeto tipo diccionario que permite acceder a datos
    :return: objeto que se encarga de renderar access.html
    :rtype: render
    """
    usuarios = Usuario.objects.order_by('id'). \
        exclude(is_superuser=True)

    if request.method == 'POST':
        usuarios = request.POST
        Usuario.objects.update(is_active=False)
        Usuario.objects.update(is_gerente=False)
        for id_usuario, valor in usuarios.items():
            if id_usuario != 'csrfmiddlewaretoken':
                if id_usuario.isnumeric() or \
                        id_usuario.split('g')[1].isnumeric():

                    # si encuentra una g antes es el campo gerente
                    if id_usuario.find('g') == 0:
                        Usuario.objects.filter(
                            id=id_usuario.split('g')[1]
                        ).update(is_gerente=valor)

                    # sino es el campo is_active
                    else:
                        Usuario.objects.filter(
                            id=id_usuario
                        ).update(is_active=valor)
        return redirect('login:index')

    return render(
        request,
        'login/access.html',
        {'usuarios': usuarios, }
    )


def user_register(request):
    """
    Vista que se encarga de registrar a un usuario

    :param request: objeto tipo diccionario que permite acceder a datos
    :return: objeto que se encarga de renderar register.html
    :rtype: render
    """

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login:login')
    else:
        form = RegisterForm()
    return render(request, 'login/register.html', {'form': form})


def user_update(request, name):
    """
    Vista encargada de la modificacion de datos de los usuarios

    :param request: objeto tipo diccionario que permite acceder a datos
    :param name: nombre del usuario a modificar
    :return: objeto que se encarga de renderar user_update.html
    :rtype: render
    """
    instance = Usuario.objects.get(username=name)
    if request.method == 'POST':
        form = UpdateUserForm(
            request.POST,
            instance=instance,
        )
        if form.is_valid():
            form.update(key=name)
            return redirect('login:index')

    else:
        form = UpdateUserForm(
            instance=instance,
            initial={'username': name}
        )

    return render(
        request=request,
        template_name='login/user_update.html',
        context={
            'form': form,
        }
    )


def auditoria(request, tipo):
    """
    Vista que se encarga de mostrar los datos de auditoría general para proyectos, items, lineas base, login, etc

    :param request: objeto de tipo diccionario que permite acceder a los datos
    :param tipo: el tipo de auditoría que se quiere realizar
    :return: objeto que se encarga de renderear auditoria.html
    :rtype: render
    """
    # primero verificamos que sea gerente o super user
    usuario = Usuario.objects.get(pk=request.user.id)
    if not (usuario.is_gerente or usuario.is_superuser):
        return redirect('administracion:accesoDenegado', id_proyecto=1, caso='auditoria')
    # si es gerente o super user continuamos
    lista = []
    mostrar_proyecto = True
    if tipo == 'proyecto':
        lista = Proyecto.history.all()
        mostrar_proyecto = False
    elif tipo == 'tipoItem':
        lista = TipoItem.history.all()
        mostrar_proyecto = False
    elif tipo == 'fase':
        lista = Fase.history.all()
    elif tipo == 'rol':
        lista = Rol.history.all()
    elif tipo == 'Lineas Base':
        lista = LineaBase.history.all()
        mostrar_proyecto = False
    elif tipo == 'Participante':
        lista = HistoricalParticipante.objects.all().order_by('id').reverse()
    elif tipo == 'acceso':
        lista = HistoricalAccesos.objects.all().order_by('id').reverse()
        mostrar_proyecto = False
    elif tipo == 'Item':
        lista = HistoricalItem.objects.all().order_by('id').reverse()
    return render(request, 'configuracion/auditoria.html', {'tipo': tipo, 'lista': lista,
                                                            'mostrar_proyecto': mostrar_proyecto})

templates/login/access.html
{% extends 'login/loginHeader.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <h1 class="col-12 text-center">Gestion de Usuarios</h1>
        <h5 class="col-12 text-center mt-3">
            Seleccione los permisos sobre el sistema que deseee proporcionar
            a los usuarios
        </h5>

        <div class="row justify-content-center mt-3">
            <form class="row col-sm-9 col-md-9 col-lg-9 pt-6" method="post">
                {% csrf_token %}
                
                <table class="table users table-hover">
                    <tr>
                        <th>Usuario</th>
                        <th>Dirección correo electrónico</th>
                        <th>Activo</th>
                        <th>Gerente</th>
                        <th></th>
                    </tr>
                    {% for usuario in usuarios %}
                        <tr>
                            <td>
                                <label> {{ usuario }} </label>
                            </td>
                            <td>
                                <label> {{ usuario.email }}</label>
                            </td>
                            {% if usuario.es_participante %}
                                <td colspan="2">
                                <h6 class="text">Usuario participante</h6>
                                </td>
                                <input name={{usuario.id}}
                                       type="checkbox"
                                       value=True
                                       hidden="true"
                                       {% if usuario.is_active%}
                                           checked
                                       {% endif %}
                                >
                                <input name="g{{usuario.id}}"
                                       type="checkbox"
                                       value=True
                                       hidden="true"
                                       {% if usuario.is_gerente%}
                                           checked
                                       {% endif %}
                                >

                            {% else %}
                                <td>
                                    <input name={{usuario.id}}
                                           type="checkbox"
                                           value=True
                                           {% if usuario.is_active%}
                                               checked
                                           {% endif %}
                                    >
                                </td>
                                <td>
                                    <input name="g{{usuario.id}}"
                                           type="checkbox"
                                           value=True
                                           {% if usuario.is_gerente%}
                                               checked
                                           {% endif %}
                                    >
                                </td>
                            {% endif %}
                            <td>
                                <a type="button"
                                        class="btn btn-primary"
                                        href={% url 'login:userUpdate' usuario %}
                                        >
                                        Editar
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <div id="accordianId" class="col-sm-12 " role="tablist" aria-multiselectable="true" >
                <div class="card ">
                    <div class="card-header d-flex flex-row-reverse " role="tab" id="sectionHeaderId">
                        <button type="submit" class="btn btn-primary m-1">Guardar</button>
                        <button type="button" class="btn btn-primary m-1" onclick="history.back()">
                            Volver
                        </button>
                        <button class="btn btn-primary m-1" type="button" data-toggle="collapse"
                                data-target="#sectionContentId"
                                aria-expanded="false"
                                aria-controls="sectionContentId">
                                Ayuda
                        </button>
                    </div>
                    <div id="sectionContentId" class="collapse in" role="tabpanel"
                         aria-labelledby="sectionHeaderId">
                        <div class="card-body">
                            <div id="accordianId" role="tablist" aria-multiselectable="true">
                                <div class="card">
                                    <div class="card-header" role="tab" id="section1HeaderId">
                                        <h5 class="mb-0">
                                            <a data-toggle="collapse" data-parent="#accordianId"
                                               href="#section1ContentId" aria-expanded="true"
                                               aria-controls="section1ContentId">
                                                Activo
                                            </a>
                                        </h5>
                                    </div>
                                    <div id="section1ContentId" class="collapse in" role="tabpanel"
                                         aria-labelledby="section1HeaderId">
                                        <div class="card-body">
                                            El campo Activo se refiere a que un usuario tiene los permisos para
                                            acceder a las funcionalidades del sistema, al estar desactivado
                                            la cuenta no sera habilitada para acceder a los datos del sistema.
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-header" role="tab" id="section2HeaderId">
                                        <h5 class="mb-0">
                                            <a data-toggle="collapse" data-parent="#accordianId"
                                               href="#section2ContentId" aria-expanded="true"
                                               aria-controls="section2ContentId">
                                                Gerente
                                            </a>
                                        </h5>
                                    </div>
                                    <div id="section2ContentId" class="collapse in" role="tabpanel"
                                         aria-labelledby="section2HeaderId">
                                        <div class="card-body">
                                            El campo gerente se refiere a que un usuario tiene los permisos de
                                            gerente, si este campo esta activo, el usuario podra tendra la
                                            posibilidad de crear nuevos proyectos dentro del sistema.
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-header" role="tab" id="HeaderUsuarioParticipate">
                                        <h5 class="mb-0">
                                            <a data-toggle="collapse" data-parent="#accordianId"
                                               href="#contenidoUsuarioParticipante" aria-expanded="true"
                                               aria-controls="contenidoUsuarioParticipante">
                                                Usuario Participante
                                            </a>
                                        </h5>
                                    </div>
                                    <div id="contenidoUsuarioParticipante" class="collapse in" role="tabpanel"
                                         aria-labelledby="HeaderUsuarioParticipate">
                                        <div class="card-body">
                                            Indica que ese usuario ya participa dentro de algun proyecto, por
                                            tanto, su cuenta no puede ser desactivada mientras que el proyecto
                                            este aun en ejecucion
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/login/admin.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <main role="main" class="container">
                <div class="d-flex align-items-center p-3 my-3  bg-purple rounded shadow-sm">
                    <h2>Bienvenido a Item Manager - Administrador</h2>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <a  class="btn btn-block btn-primary text-white" 
                            href="{% url 'login:administrarAccesos' %}">
                            Administrar Accesos de los usuarios
                        </a>
                    </div>
                </div>

            </main>
        </div>
    </div>
{% endblock %}

templates/login/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <main role="main" class="container">
                <div class="d-flex align-items-center p-3 my-3  bg-purple rounded shadow-sm">
                <h2 class="">Bienvenido a Item Manager</h2>
                </div>

                <h4 class="pb-3">Seleccione Un Módulo: </h4>
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <a class="btn btn-block btn-primary text-white" href="{% url 'administracion:proyectos' 'todos' %}">
                            Modulo de administracion
                        </a>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <a class="btn btn-block btn-primary text-white" href="{% url 'desarrollo:indexDesarrollo' 'todos' %}">
                            Modulo de desarrollo
                        </a>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <a class="btn btn-block btn-primary text-white" href="{% url 'configuracion:indexConfiguracion' 'todos' %}">
                            Modulo de configuracion
                        </a>
                    </div>
                </div>

            </main>
        </div>
    </div>
{% endblock %}

templates/login/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Login</title>
    {% load static %}

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Bienvenido!</h1>
                  </div>
                  <form class="user" method="post">
                      {% csrf_token %}
                    {%  if error_message %}
                        <div class="form-group">
                            <div class=" alert alert-danger">
                                {{ error_message }}
                            </div>
                        </div>
                    {%  endif %}
                    <div class="form-group">
                      <input name="email" type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Ingrese su correo...">
                    </div>
                    <div class="form-group">
                      <input name="password" type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Ingrese su contraseña...">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">Ingresar</button>
                  </form>

                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'login:register' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/login/loginHeader.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

templates/login/postReg.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <div>

            <h3>Usuario creado con exito!</h3>

            <h3><a href="{% url 'login:login' %}">Acceder</a></h3>
            <h3><a href="{% url 'login:register' %}">Registrar nuevo usuario</a></h3>
        </div>
    </div>
{% endblock %}