ItemManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('administracion/', include('administracion.urls')),
    path('desarrollo/', include('desarrollo.urls')),
    path('configuracion/', include('configuracion.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

administracion/urls.py
from django.urls import path

from administracion import views

app_name = 'administracion'
urlpatterns = [

    # URL DE PAO
    path('proyectos/<int:id_proyecto>/roles/crear/', views.crear_rol, name='crearRol'),
    path('proyectos/<int:id_proyecto>/roles', views.administrar_roles, name='administrarRoles'),
    path('proyectos/<int:id_proyecto>/roles/<int:id_rol>/desactivar/', views.desactivar_rol_proyecto, name='desactivarRol'),
    path('proyectos/<int:id_proyecto>/usuario/<int:id_usuario>/roles', views.ver_roles_usuario, name='verRolesUsuario'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>/roles/<int:id_rol>', views.desasignar_rol_al_usuario, name='desasignarRol'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>', views.asignar_rol_por_fase, name='asignarRol'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>/rol/<int:id_rol>', views.registrar_rol_por_fase, name='registrarRolPorFase'),
    # URLs DE MATI
    path('proyectos/<str:filtro>', views.proyectos, name='proyectos'),
    path('proyectos/crear/', views.crear_proyecto, name='crearProyecto'),
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    path('proyectos/<int:id_proyecto>/participantes', views.administrar_participantes, name='administrarParticipantes'),
    path('proyectos/<int:id_proyecto>/editar', views.editar_proyecto, name='editarProyecto'),
    path('proyectos/<int:id_proyecto>/estado', views.estado_proyectov2, name='estadoProyecto'),
    path('proyectos/<int:id_proyecto>/estado/<str:estado>', views.estado_proyectov2, name='estadoProyecto2'),
    path('proyectos/<int:id_proyecto>/adminfases', views.administrar_fases_del_proyecto, name='administrarFasesProyecto'),
    path('proyectos/<int:id_proyecto>/comite', views.administrar_comite, name='administrarComite'),
    path('proyectos/<int:id_proyecto>/<int:id_usuario>/<str:caso>', views.eliminar_participante_y_comite, name='desasignarUsuario'),
    path('proyectos/<int:id_proyecto>/accesodenegado/<str:caso>', views.acceso_denegado, name='accesoDenegado'),
    path('proyectos/<int:id_proyecto>/auditoria/<str:tipo>/', views.auditoria_particular, name='auditoriaParticular'),
    # URLs de DAVID
    path('tipo/todos', views.mostrar_tipo_item, name='tipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/showForImport', views.mostrar_tipo_import, name='importarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/mostrarImport', views.confirmar_tipo_import, name='confirmarImportarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/import', views.importar_tipo, name='importarTipoItemAProyecto'),
    path('proyectos/<int:id_proyecto>/tipo/', views.ver_tipo_por_proyecto, name='tipoItemPorProyecto'),
    path('proyectos/<int:id_proyecto>/tipo/crear/', views.crear_tipo, name='crearTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/editar/', views.editar_tipo, name='editarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/desactivar/', views.desactivar_tipo_item, name='desactivarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/registrarEnBase', views.registrar_tipoitem_en_base, name='registrarEnBase'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>', views.ver_tipo, name='verTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/atributo/crear', views.crear_atributo, name='crearAtributo'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/atributo/<int:id_atributo>/quitar/', views.quitar_atributo, name='quitarAtributo'),
]

configuracion/urls.py
from django.urls import path

from configuracion import views

app_name = 'configuracion'
urlpatterns = [
    # URLs de Mati
    path('<str:filtro>', views.index, name='indexConfiguracion'),
    path('proyectos/<int:id_proyecto>/item/<int:id_item>/trazabilidad', views.trazabilidad, name='trazabilidad'),
    path('proyectos/<int:id_proyecto>/item/<int:id_item>/trazabilidad/reporte', views.reporte_trazabilidad, name='reporteTrazabilidad'),

    # URLs de David
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    path('proyectos/fase/<int:id_fase>/crearLB', views.crear_linea_base, name='crearLineaBase'),
    path('proyectos/fase/lineabase/<int:id_lineabase>', views.ver_linea_base, name='verLineaBase'),
    path('proyectos/<int:id_proyecto>/comite/', views.comite_index, name='verIndexComite'),
    path('proyectos/<int:id_proyecto>/comite/<int:id_solicitud>/votar/<int:voto>', views.votar_solicitud, name='votarSolicitud'),
    path('proyectos/<int:id_proyecto>/cerrar', views.cerrar_proyecto, name='cerrarProyecto'),
    # URLs de Fer
    path('lineabase/<int:id_lineabase>', views.solicitud_ruptura, name='solicitudRuptura'),
    path('proyectos/<int:id_proyecto>/reporte', views.reporte, name='reporte'),

    # URLs de Pao
    path('proyectos/<int:id_proyecto>/item/<int:id_item>/solicitarDesaprobar', views.solicitud_modificacion_estado, name='solicitarModificarEstado'),
    #path('proyectos/<int:id_proyecto>/comite/<int:id_solicitud>/votarItem/<int:voto>', views.votar_solicitud_desaprobacion, name='votarSolicitudDesaprobacion')

]

desarrollo/urls.py
from django.urls import path

from desarrollo import views

app_name = 'desarrollo'
urlpatterns = [
    # URLs de Mati
    path('fase/<int:id_fase>/tipo/<int:id_tipo>/items/crear', views.crear_item, name='crearItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>', views.ver_item, name='verItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/historialversiones', views.historial_versiones_item,
         name='histVersionesItem'),
    path('proyectos/<int:id_proyecto>/aprobacion', views.menu_aprobacion, name='menuAprobacion'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/reversionar/<int:id_version_anterior>', views.reversionar_item,
         name='reversionarItem'),
    # path('items/<int:id_item>/calculo_impacto', views.calculo_de_impacto, name='calculoDeImpacto'),
    # URLs de David
    path('<str:filtro>', views.index, name='indexDesarrollo'),
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    # URLs de Fer
    path('proyectos/<int:id_proyecto>/relacionar', views.relacionar_item, name='relacionar'),
    path('proyectos/<int:id_proyecto>/desactivar_relacion', views.desactivar_relacion_item, name='desactivarRelacion'),
    path('proyectos/<int:id_proyecto>/cerrar_fase', views.cerrar_fase, name='cerrarFase'),
    # URLs de Pao
    path('items/<int:id_item>/solicitar', views.solicitud_aprobacion, name='solicitarAprobacion'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/desactivar', views.desactivar_item, name='desactivarItem'),
    path('items/<int:id_item>/aprobar', views.aprobar_item, name='aprobarItem'),
    path('items/<int:id_item>/desaprobar', views.desaprobar_item, name='desaprobarItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/editar', views.modificar_item, name='editarItem'),
    path('items/<int:id_item>/votar', views.votacion_item_en_revision_desarrollo, name='votacionItem'),
    path('items/<int:id_item>/votar2', views.votacion_item_en_revision_aprobado, name='votacionItem2'),
    path('items/<int:id_item>/votar3', views.votacion_item_en_revision_lineaBase, name='votacionItem3')
]

login/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.user_register, name='register'),

    path('admin/', views.admin, name='admin'),
    path('admin/access/', views.users_access, name='administrarAccesos'),
    path('<str:name>/update/', views.user_update, name='userUpdate'),
    path(
        'accesoDenegado/',
        TemplateView.as_view(template_name='login/accesoDenegado.html'),
        name='AccesoDenegado',
    ),

    # urls de Mati
    path('auditoria/<str:tipo>', views.auditoria, name='auditoria'),
]

configuracion/models.py
"""
Models del modulo de configuracion
"""
from django.db import models
from simple_history.models import HistoricalRecords

from desarrollo.models import Item
from django.utils.timezone import now
from desarrollo.models import Fase


# Create your models here.


class LineaBase(models.Model):
    """
    clase que representa a una linea base
    """
    #: lista de items de la linea base
    items = models.ManyToManyField(Item)
    fecha_creacion = models.DateField(default=now)
    creador = models.ForeignKey('login.Usuario', on_delete=models.CASCADE, default=None, null=True)
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE, null=False)
    ESTADO_CERRADA = 'Cerrada'
    ESTADO_ROTA = 'Rota'
    TIPO_PARCIAL = 'Parcial'
    TIPO_TOTAL = 'Total'
    tipo = models.CharField(max_length=100, default=TIPO_PARCIAL)
    #: estado actual de la linea base
    estado = models.CharField(max_length=100, default=ESTADO_CERRADA, null=False)
    #: atributo para enumerar las lineas base dentro de un proyecto
    numeracion = models.IntegerField(default=1)
    #: campo que sirve para realizar auditoría de los objetos del modelo
    history = HistoricalRecords()


class Solicitud(models.Model):
    """
    Clase que representa la solicitud de cambios
    """
    items_a_modificar = models.ManyToManyField(Item)
    fecha_solicitud = models.DateField(default=now)
    solicitado_por = models.ForeignKey('login.Usuario', on_delete=models.CASCADE, default=None, null=True)
    linea_base = models.ForeignKey('configuracion.LineaBase', on_delete=models.CASCADE, default=None, null=True)
    justificacion = models.CharField(max_length=200, null=False)
    solicitud_activa = models.BooleanField(default=True)

    def ha_votado(self, votante):
        for voto in self.votoruptura_set.all():
            if voto.votante == votante:
                return True
        return False


class VotoRuptura(models.Model):
    """
    Clase que representa un voto del comite
    """
    solicitud = models.ForeignKey(Solicitud, null=False, on_delete=models.DO_NOTHING)
    votante = models.ForeignKey('login.Usuario', null=False, on_delete=models.DO_NOTHING)
    valor_voto = models.BooleanField(default=False)  # TRUE a favor FALSE en contra
    fecha_voto = models.DateField(default=now)

desarrollo/models.py
"""
Mapeador objeto-relacional en el que es posible definir la estructura de la base de datos utilizando código Python.
"""
from django.db import models
from administracion.models import Fase
from django.utils.timezone import now


class Item(models.Model):
    """
    clase que representa a los ítems que son instanciados a partir de un tipo de ítem
    """
    #: nombre que identifica al ítem
    nombre = models.CharField(max_length=200, null=False)
    #: estado actual, puede tomar los valores: en desarrollo, pendiente de aprobación, aprobado, desactivado,
    # en revisión, en línea base
    estado = models.CharField(max_length=100, default='En Desarrollo', null=False)
    numeracion = models.IntegerField(default=1)
    #: version actual del ítem que va cambiando luego de cada nueva relación y cada modificación de sus datos
    version = models.PositiveIntegerField(null=False, default=1)
    #: valor que define el impacto del ítem en el proyecto. Toma valores enteros entre 1 y 10
    complejidad = models.PositiveIntegerField(default=5, null=False)
    #: comentarios opcionales para describir al ítem
    descripcion = models.CharField(max_length=200, null=True)
    #: tipo que tendrá el ítem, de eso dependen sus atributos particulares
    tipo_item = models.ForeignKey('administracion.TipoItem', on_delete=models.CASCADE)
    #: fase del proyecto en la que se crea el ítem
    fase = models.ForeignKey('administracion.Fase', on_delete=models.CASCADE, default=None, blank=True, null=True)
    #: versión anterior a la del item actual
    version_anterior = models.ForeignKey('desarrollo.Item', on_delete=models.CASCADE, default=None, null=True)
    #: id para identificar a todas las versiones de un mismo ítem
    id_version = models.IntegerField(null=True)

    # listas para las relaciones del ítem
    antecesores = models.ManyToManyField('Item', related_name='item_desarrollo_antecesores', blank=True)
    sucesores = models.ManyToManyField('Item', related_name='item_desarrollo_sucesores', blank=True)
    padres = models.ManyToManyField('Item', related_name='item_desarrollo_padres', blank=True)
    hijos = models.ManyToManyField('Item', related_name='item_desarrollo_hijos', blank=True)

    # constantes del modelo
    ESTADO_DESARROLLO = 'En Desarrollo'
    ESTADO_PENDIENTE = 'Pendiente de Aprobacion'
    ESTADO_APROBADO = 'Aprobado'
    ESTADO_REVISION = 'En Revision'
    ESTADO_LINEABASE = 'En Linea Base'
    ESTADO_DESACTIVADO = 'Desactivado'

    def __str__(self):
        return self.nombre

    def es_ultima_version(self):
        ultima_item_version = Item.objects.filter(id_version=self.id_version, estado__regex='^(?!' + Item.ESTADO_DESACTIVADO + ')'
                                   ).order_by('version').last()
        return ultima_item_version.version == self.version

    def get_ultima_version(self):
        return Item.objects.filter(id_version=self.id_version, estado__regex='^(?!' + Item.ESTADO_DESACTIVADO + ')'
                                   ).order_by('version').last()


class AtributoParticular(models.Model):
    """
    Esta clase representa cada uno de los atributos extra que tiene un ítem dependiendo de su tipo de ítem
    """
    #: item al cual pertenecen estos atributos
    item = models.ForeignKey('desarrollo.Item', on_delete=models.CASCADE, default=None)
    #: nombre del atributo
    nombre = models.CharField(max_length=200, null=False)
    #: tipo del atributo, puede tomar valores: text, numeric, file, date
    tipo = models.CharField(max_length=100, null=False)
    #: valor que es almacenado dentro del atributo
    valor = models.CharField(max_length=300)

    def __str__(self):
        return self.nombre


class HistoricalItem(models.Model):
    """
    Clase que sirve para guardar datos de auditoría para cada item del proyecto
    """
    #: usuario que participa en el proyecto
    item = models.ForeignKey('desarrollo.Item', on_delete=models.CASCADE)
    #: usuario que realizó la acción
    history_user = models.CharField(max_length=150, default='None')
    #: fecha y hora en la que se realizó la acción
    history_date = models.DateTimeField(default=now)
    #: razón de cambio (nulo por defecto)
    history_change_reason = models.CharField(max_length=200, null=True)
    #: tipo de cambio: puede ser crear, modificar, eliminar, reversionar, cambiar estado, relacionar, desrelacionar
    history_type = models.CharField(max_length=250)
    # constantes
    TIPO_CREAR = '+'
    TIPO_MODIFICAR = '~'
    TIPO_ELIMINAR = '-'
    TIPO_REVERSIONAR = 'reversión'
    TIPO_ESTADO = 'estado cambiado a '
    TIPO_RELACIONAR = 'relación creada'
    TIPO_DESRELACIONAR = 'relación eliminada'

templates/configuracion/auditoria.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center pt-3 mb-5">Auditoría de {% if not audit_particular %}{{ tipo }}s{% else %}{{ proyecto.nombre }}({{ tipo }}){% endif %}</h1>
        <div class="table-responsive" style="overflow-y: auto;">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Id Historial</th>
                        {% if tipo != 'acceso' %}
                            <th>Nombre de {{ tipo }}</th>
                        {% endif %}
                        {% if mostrar_proyecto %}
                            <th>Proyecto</th>
                        {% endif %}
                        <th>Tipo de acción</th>
                        <th>Usuario</th>
                        <th>Fecha y hora</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in lista %}
                        <tr>
                            <td>{% if tipo != 'Participante' and tipo != 'acceso' and tipo != 'Item' %}
                                    {{ elemento.history_id }}
                                {% else %}
                                    {{ elemento.id }}
                                {% endif %}
                            </td>
                            {% if tipo != 'acceso' %}
                                <td>{% if tipo == 'proyecto' %}
                                        <a href="{% url 'administracion:verProyecto' elemento.id %}">{{ elemento.nombre }}</a>
                                    {% elif tipo == 'tipoItem' %}
                                        {{ elemento.nombre }} [{{ elemento.prefijo }}]
                                    {% elif tipo == 'fase' %}
                                        <strong>
                                            {% if  elemento.nombre  %}
                                                {{ elemento.nombre }}
                                            {% else %}
                                                Nombre sin definir
                                            {% endif %}
                                        </strong>
                                    {% elif tipo == 'rol' %}
                                        {{ elemento.nombre }}
                                    {% elif tipo == 'Lineas Base' %}
                                        Línea Base {{ elemento.numeracion }} de {{ elemento.fase.proyecto }}
                                    {% elif tipo == 'Participante' %}
                                        {{ elemento.usuario }}
                                    {% elif tipo == 'Item' %}
                                        <a href="{% url 'desarrollo:verItem' elemento.item.fase.proyecto.id elemento.item.id %}">{{ elemento.item }}</a>
                                    {% endif %}</td>
                            {% endif %}
                            {% if mostrar_proyecto %}
                                <td>
                                    {% if tipo != 'Item' %}
                                        {{ elemento.proyecto }}
                                    {% else %}
                                        {{ elemento.item.fase.proyecto }}
                                    {% endif %}
                                </td>
                            {% endif %}
                            <td>{% if elemento.history_type == '+' %}
                                    creación
                                {% elif elemento.history_type == '~' %}
                                    modificación
                                {% elif elemento.history_type == '-' %}
                                    eliminación
                                {% endif %}
                                ({{ elemento.history_type }})</td>
                            <td>{{ elemento.history_user }}</td>
                            <td>{{ elemento.history_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="mt-5">
            <a href="{% url 'login:index' %}" class="btn btn-primary float-right">Volver atrás</a>
        </div>
    </div>
{% endblock %}

templates/configuracion/lineabase_ver.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center pt-3 mb-3">{{ lineabase.fase.nombre }} - Linea Base {{ lineabase.id }}</h1>
        <table class="table">
            <tbody>
                <tr>
                    <td>Creador</td>
                    <td>{{ lineabase.creador.username }}</td>
                </tr>
                <tr>
                    <td>Fecha de creacion</td>
                    <td>{{ lineabase.fecha_creacion }}</td>
                </tr>
                <tr>
                    <td>Tipo</td>
                    <td>{{ lineabase.tipo }}</td>
                </tr>
                <tr>
                    <td>Estado</td>
                    <td>{{ lineabase.estado }}</td>
                </tr>
                <tr>
                    <td>Items</td>
                    <td>
                        <ul>
                            {% for item in lineabase.items.all %}
                                <li>{{ item.tipo_item.prefijo }} {% if item.numeracion < 10 %}0{% endif %}{{ item.numeracion    }}-{{ item.nombre }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mt-3">
            <a href="{% url 'configuracion:verProyecto' lineabase.fase.proyecto.id %}" class="btn btn-primary">Volver atras</a>
            {% if lineabase.solicitud_set.all.count != 0 %}
                <button class="btn btn-primary" disabled="true">Ruptura solicitada</button>
            {% elif lineabase.fase.estado == lineabase.fase.FASE_ESTADO_CERRADA %}
                <button class="btn btn-primary" disabled="true">Fase cerrada</button>
            {% else %}
                <a href="{% url 'configuracion:solicitudRuptura' lineabase.id %}" class="btn btn-primary">Solicitar ruptura</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/configuracion/proyecto_ver_unico.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center pt-3 mb-3">{{ proyecto.nombre }}</h1>
        <h4 class="text-center">(Se muestran los items aprobados y en Linea Base)</h4>
        <div class="btn float-right">

        </div>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    {% for fase in proyecto.fase_set.all %}
                        <th class="">
                            <div>{{ fase.nombre }}</div>
                        </th>
                    {% endfor %}

                </tr>
            </thead>
            <tbody>
                <tr class="">
                    {% for fase in proyecto.fase_set.all %}
                        <td class="justify-content-center">
                            <div class="list-group pt-2">
                                <ul>
                                    {% for item in fase.item_set.all %}
                                        {% if item.estado == item.ESTADO_APROBADO %}
                                            <li class="list-group">
                                                <a class="align-baseline"
                                                   href="{% url 'configuracion:trazabilidad' proyecto.id item.id %}" >
                                                   {{ item.tipo_item.prefijo }} {% if item.numeracion < 10 %}0{% endif %}{{ item.numeracion    }}-{{ item.nombre }}
                                                </a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                                {% for linea_base in fase.lineabase_set.all %}
                                    {% if linea_base.estado == linea_base.ESTADO_CERRADA and linea_base.items.count >= 1 %}
                                        <ul class="listaEnLB">
                                        <h5 class="fieldset-title">
                                            <a class="text-primary" href="{% url 'configuracion:verLineaBase' linea_base.id %}"  >
                                                Linea Base {% if linea_base.numeracion < 10 %}0{% endif %}{{ linea_base.numeracion }}
                                            </a>
                                        </h5>
                                        {% for item in linea_base.items.all %}
                                            <li class="list-group">
                                                <a class="align-baseline text-secondary"
                                                   href="{% url 'configuracion:trazabilidad' proyecto.id item.id %}" >
                                                   {{ item.tipo_item.prefijo }} {% if item.numeracion < 10 %}0{% endif %}{{ item.numeracion    }}-{{ item.nombre }}
                                                </a>
                                            </li>
                                        {% endfor %}
                                        </ul>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </td>
                    {% endfor %}
                </tr>
            </tbody>
            <tfoot>
                <tr>
                {% for fase in proyecto.fase_set.all %}
                    <td>
                        <a class="btn btn-info btn-block" href="{% url 'configuracion:crearLineaBase' fase.id %}">
                            Crear linea base
                        </a>
                    </td>
                {% endfor %}
                </tr>
            </tfoot>
        </table>

        <div class="col-sm-12 mt-4">
            {% if es_comite %}
                <a class="btn btn-primary" href="{% url 'configuracion:verIndexComite' proyecto.id %}">Comite de decisiones</a>
            {% endif %}
            {% if puede_cerrar %}
                <a class="btn btn-primary" href="{% url 'configuracion:cerrarProyecto' proyecto.id %}">Cerrar proyecto</a>
            {% endif %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Generar reporte</button>
            <a href="{% url 'configuracion:indexConfiguracion' 'todos' %}" class="btn btn-primary float-right">Volver atrás</a>
        </div>
{#        Modal reporte #}
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> Generar reporte</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form id="reporteForm" action="{% url 'configuracion:reporte'  proyecto.id %}" method="post">
                    {% csrf_token %}
                    <h4>Seleccione las fases que quiere incluir al reporte</h4>
                    {% for fase in proyecto.fase_set.all %}
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="checkFase-{{ fase.id }}" id="checkFase-{{ fase.id }}">
                        <label class="form-check-label" for="checkFase-{{ fase.id }}">{{ fase.nombre }}</label>
                      </div>
                    {% endfor %}
                    <hr>
                    <h4>Seleccione el rango para ver la cantidad de solicitudes de cambio en el reporte</h4>
                    <div class="form-group">
                        <label for="inicio" class="col-form-label">Fecha Inicio:</label>
                        <input type="date" class="form-group" id="inicio" name="inicio" required>
                    </div>
                    <div class="form-group">
                        <label for="fin" class="col-form-label">Fecha Fin:</label>
                        <input type="date" class="form-group" id="fin" name="fin" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="reporteButton" type="submit" class="btn btn-primary" onclick="submitReporte()">Descargar PDF</button>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>
    <script>
        const pintarLB = ()=> {
            const enLB = document.getElementsByClassName('listaEnLB');
            for (i = 0; i < enLB.length; i++) {
                let item = enLB[i];
                if (item.childElementCount > 0) {
                    item.classList.add('border');
                    item.classList.add('border-primary');
                }
            }
        };
        pintarLB();
        const submitReporte = ()=>{
            form =  document.getElementById('reporteForm');
            if(form.checkValidity()){
                form.submit();
                $('#exampleModal').modal('hide');
            }
        };

    </script>
{% endblock %}