ItemManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('administracion/', include('administracion.urls')),
    path('desarrollo/', include('desarrollo.urls')),
    path('configuracion/', include('configuracion.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

administracion/urls.py
from django.urls import path

from administracion import views

app_name = 'administracion'
urlpatterns = [

    # URL DE PAO
    path('proyectos/<int:id_proyecto>/roles/crear/', views.crear_rol, name='crearRol'),
    path('proyectos/<int:id_proyecto>/roles', views.administrar_roles, name='administrarRoles'),
    path('proyectos/<int:id_proyecto>/roles/<int:id_rol>/desactivar/', views.desactivar_rol_proyecto, name='desactivarRol'),
    path('proyectos/<int:id_proyecto>/usuario/<int:id_usuario>/roles', views.ver_roles_usuario, name='verRolesUsuario'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>/roles/<int:id_rol>', views.desasignar_rol_al_usuario, name='desasignarRol'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>', views.asignar_rol_por_fase, name='asignarRol'),
    path('fases/<int:id_fase>/usuario/<int:id_usuario>/rol/<int:id_rol>', views.registrar_rol_por_fase, name='registrarRolPorFase'),
    # URLs DE MATI
    path('proyectos/<str:filtro>', views.proyectos, name='proyectos'),
    path('proyectos/crear/', views.crear_proyecto, name='crearProyecto'),
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    path('proyectos/<int:id_proyecto>/participantes', views.administrar_participantes, name='administrarParticipantes'),
    path('proyectos/<int:id_proyecto>/editar', views.editar_proyecto, name='editarProyecto'),
    path('proyectos/<int:id_proyecto>/estado', views.estado_proyectov2, name='estadoProyecto'),
    path('proyectos/<int:id_proyecto>/estado/<str:estado>', views.estado_proyectov2, name='estadoProyecto2'),
    path('proyectos/<int:id_proyecto>/adminfases', views.administrar_fases_del_proyecto, name='administrarFasesProyecto'),
    path('proyectos/<int:id_proyecto>/comite', views.administrar_comite, name='administrarComite'),
    path('proyectos/<int:id_proyecto>/<int:id_usuario>/<str:caso>', views.eliminar_participante_y_comite, name='desasignarUsuario'),
    path('proyectos/<int:id_proyecto>/accesodenegado/<str:caso>', views.acceso_denegado, name='accesoDenegado'),
    path('proyectos/<int:id_proyecto>/auditoria/<str:tipo>/', views.auditoria_particular, name='auditoriaParticular'),
    # URLs de DAVID
    path('tipo/todos', views.mostrar_tipo_item, name='tipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/showForImport', views.mostrar_tipo_import, name='importarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/mostrarImport', views.confirmar_tipo_import, name='confirmarImportarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/import', views.importar_tipo, name='importarTipoItemAProyecto'),
    path('proyectos/<int:id_proyecto>/tipo/', views.ver_tipo_por_proyecto, name='tipoItemPorProyecto'),
    path('proyectos/<int:id_proyecto>/tipo/crear/', views.crear_tipo, name='crearTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/editar/', views.editar_tipo, name='editarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/desactivar/', views.desactivar_tipo_item, name='desactivarTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/registrarEnBase', views.registrar_tipoitem_en_base, name='registrarEnBase'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>', views.ver_tipo, name='verTipoItem'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/atributo/crear', views.crear_atributo, name='crearAtributo'),
    path('proyectos/<int:id_proyecto>/tipo/<int:id_tipo>/atributo/<int:id_atributo>/quitar/', views.quitar_atributo, name='quitarAtributo'),
]

login/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.user_register, name='register'),

    path('admin/', views.admin, name='admin'),
    path('admin/access/', views.users_access, name='administrarAccesos'),
    path('<str:name>/update/', views.user_update, name='userUpdate'),
    path(
        'accesoDenegado/',
        TemplateView.as_view(template_name='login/accesoDenegado.html'),
        name='AccesoDenegado',
    ),

    # urls de Mati
    path('auditoria/<str:tipo>', views.auditoria, name='auditoria'),
]

administracion/models.py
"""
Mapeador objeto-relacional en el que es posible definir la estructura de la base de datos utilizando código Python.
"""
from django.db import models
from simple_history.models import HistoricalRecords
from django.utils.timezone import now


# Create your models here.

class Proyecto(models.Model):
    """
    Clase que representa a los proyectos que administrará el sistema con sus respectivos atributos
    """
    #: nombre del proyecto
    nombre = models.CharField(max_length=200, null=False)
    #: fecha en la que el proyecto comienza
    fecha_inicio = models.DateField(auto_now=False, auto_now_add=False)
    #: fecha y hora en la que el proyecto pasa a estado de ejecución
    fecha_ejecucion = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
    #: fecha y hora en la que el proyecto pasa a finalizado
    fecha_finalizado = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
    #: fecha y hoar en la que el proyecto pasa a cancelado
    fecha_cancelado = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
    #: estado actual del proyecto, puede variar entre iniciado, en ejecución, cancelado, finalizado
    estado = models.CharField(max_length=200, default='iniciado')
    #: cantidad de fases que tiene el proyecto
    numero_fases = models.IntegerField(null=False)
    #: cantidad de miembros que deberá tener el comité, debe ser impar y mayor o igual a 3
    cant_comite = models.IntegerField(null=False)
    #: usuario que toma el rol de gerente del proyecto
    gerente = models.IntegerField(null=False)
    #: conjunto impar de usuarios que conforma el comité para el proyecto
    comite = models.ManyToManyField('login.Usuario', related_name='usuario_login_comite')
    #: equipo de usuarios que participa en el proyecto
    participantes = models.ManyToManyField('login.Usuario', related_name='usuario_login_participante')
    #: campo que sirve para realizar auditoría de los objetos del modelo
    history = HistoricalRecords()

    ESTADO_CANCELADO = 'cancelado'
    ESTADO_INICIADO = 'iniciado'
    ESTADO_EN_EJECUCION = 'en ejecucion'
    ESTADO_FINALIZADO = 'finalizado'

    def __str__(self):
        return self.nombre

    def es_comite(self, id_usuario):
        """
        función booleana que retorna true si un usuario es parte del comité del proyecto

        :param id_usuario: identificar unico del usuario del que se desea saber si es parte del comité
        :return: retorna True si forma parte y False en caso contrario
        """
        for usuario in self.comite.all():
            if usuario.id == id_usuario:
                return True
        return False

    def es_participante(self, id_usuario):
        """
        función booleana para saber si un usuario es participante del proyecto

        :param id_usuario: identificador único del usuario el cual se quiere saber si es participante del proyecto
        :return: True si es participante y False en caso contrario
        """
        for usuario in self.participantes.all():
            if usuario.id == id_usuario:
                return True
        return False


class TipoItem(models.Model):
    """
    Esta clase representa los tipos de items
    """
    #: Se almacena el nombre del tipo de item
    nombre = models.CharField(max_length=200)
    #: Descripcion del tipo de item
    descripcion = models.CharField(max_length=800)
    #: Prefijo para mostrarse en todos los items instanciados de esta plantilla
    prefijo = models.CharField(max_length=5)
    #: Proyecto asociado al Tipo de Item
    proyecto = models.ManyToManyField('Proyecto')
    #: campo que sirve para realizar auditoría de los objetos del modelo
    history = HistoricalRecords()

    def __str__(self):
        return self.nombre


class PlantillaAtributo(models.Model):
    """
    Esta clase representa las plantilla de atributos usada por el tipo de item

    """
    #: Se almacena el nombre del tipo de item
    nombre = models.CharField(max_length=200)
    #: Tipo del atributo a ser instanciado
    tipo = models.CharField(max_length=100)
    #: TipoItem asociado a la plantilla
    tipo_item = models.ForeignKey(TipoItem, on_delete=models.CASCADE)
    #: Atributo que indica si completar el atributo es requerido
    es_requerido = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre


class Fase(models.Model):
    """
    Esta clase representa las fases
    """

    FASE_ESTADO_CERRADA = 'cerrada'
    FASE_ESTADO_ABIERTA = 'abierta'
    #: Se almacena el nombre de la fase
    nombre = models.CharField(max_length=200, null=False)
    #: Descripcion de la fase
    descripcion = models.CharField(max_length=400, null=True)
    #: Estado de la fase, iniciada, cerrada etc.
    estado = models.CharField(max_length=200, default=FASE_ESTADO_ABIERTA)
    #: Proyecto asociado a la fase
    proyecto = models.ForeignKey('Proyecto', on_delete=models.CASCADE)
    #: lista de tipos de ítem
    tipos_item = models.ManyToManyField('TipoItem', blank=True)
    #: campo que sirve para realizar auditoría de los objetos del modelo
    history = HistoricalRecords()

    class Meta:
        ordering = ['id']


class Rol(models.Model):
    """
    Clase que representa los roles de los usuarios en los proyectos
    """
    #: Nombre a ser asignado al Rol
    nombre = models.CharField(max_length=150, default='null')
    #: Proyecto asociado
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, null=True)
    #: Items del proyecto
    crear_item = models.BooleanField(default=False)
    #: Cambios realizados a los items del proyecto
    modificar_item = models.BooleanField(default=False)
    #: Dejar inactivo un item
    desactivar_item = models.BooleanField(default=False)
    #: Confirmar que el item es correcto
    aprobar_item = models.BooleanField(default=False)
    #: Cambiar version de un item
    reversionar_item = models.BooleanField(default=False)
    #: crear relaciones de tipo padre e hijo
    crear_relaciones_ph = models.BooleanField(default=False)
    #: crear relaciones de tipo antecesor y sucesor
    crear_relaciones_as = models.BooleanField(default=False)
    #: borrar relaciones del proyecto
    borrar_relaciones = models.BooleanField(default=False)
    #: ver Items del proyecto
    ver_item = models.BooleanField(default=False)
    #: crear lineas base en el proyecto
    crear_linea_base = models.BooleanField(default=False)
    #: cerrar fases del proyecto
    cerrar_fase = models.BooleanField(default=False)
    #: cerrar el proyecto
    cerrar_proyecto = models.BooleanField(default=False)
    #: ver proyecto
    ver_proyecto = models.BooleanField(default=False)
    #: solicitar ruptura de linea base
    solicitar_ruptura_lb = models.BooleanField(default=False)

    #: ver si el rol está activo
    activo = models.BooleanField(default=True)

    #: campo que sirve para realizar auditoría de los objetos del modelo
    history = HistoricalRecords()

    CREAR_ITEM = 'CREAR_ITEM'
    MODIFICAR_ITEM = 'MODIFICAR_ITEM'
    DESACTIVAR_ITEM = 'DESACTIVAR_ITEM'
    APROBAR_ITEM = 'APROBAR_ITEM'
    REVERSIONAR_ITEM = 'REVERSIONAR_ITEM'
    CREAR_RELACIONES_PH = 'CREAR_RELACIONES_PH'
    CREAR_RELACIONES_AS = 'CREAR_RELACIONES_AS'
    BORRAR_RELACIONES = 'BORRAR_RELACIONES'
    VER_ITEM = 'VER_ITEM'
    CREAR_LINEA_BASE = 'CREAR_LINEA_BASE'
    CERRAR_FASE = 'CERRAR_FASE'
    CERRAR_PROYECTO = 'CERRAR_PROYECTO'
    VER_PROYECTO = 'VER_PROYECTO'
    SOLICITAR_RUPTURA_LB = 'SOLICITAR_RUPTURA'

    def get_permisos_clean(self):
        """
        Metodo que colecta los permisos activos
        :return: una lista de permisos activos
        """
        permisos = []
        permisos = permisos + (['Crear Item'] if self.crear_item else [])
        permisos = permisos + (['Modificar Item'] if self.modificar_item else [])
        permisos = permisos + (['Desactivar Item'] if self.desactivar_item else [])
        permisos = permisos + (['Aprobar Item'] if self.aprobar_item else [])
        permisos = permisos + (['Reversionar Item'] if self.reversionar_item else [])
        permisos = permisos + (['Crear Relaciones Padre Hijo'] if self.crear_relaciones_ph else [])
        permisos = permisos + (['Crear Relaciones Antecesor Sucesor'] if self.crear_relaciones_as else [])
        permisos = permisos + (['Borrar Relaciones'] if self.borrar_relaciones else [])
        permisos = permisos + (['Ver Item'] if self.ver_item else [])
        permisos = permisos + (['Crear Linea Base'] if self.crear_linea_base else [])
        permisos = permisos + (['Cerrar Fase'] if self.cerrar_fase else [])
        permisos = permisos + (['Cerrar Proyecto'] if self.cerrar_proyecto else [])
        permisos = permisos + (['Ver Proyecto'] if self.ver_proyecto else [])
        permisos = permisos + (['Solicitar Ruptura Linea Base'] if self.solicitar_ruptura_lb else [])

        return permisos

    def __str__(self):
        return self.nombre


class UsuarioxRol(models.Model):
    """
    Clase en la cual se definen los roles del usuario
    """
    #: Usuario al cual le corresponde dicho rol
    usuario = models.ForeignKey('login.Usuario', on_delete=models.CASCADE)
    #: Rol del usuario
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE)
    #: Fase del proyecto al cual esta asociado el usuario
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE)
    #:
    activo = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.usuario.username} es {self.rol.nombre} en {self.fase.nombre} - {self.activo}'


class HistoricalParticipante(models.Model):
    """
    Clase que sirve para guardar datos de auditoría para participantes del proyecto
    """
    #: usuario que participa en el proyecto
    usuario = models.ForeignKey('login.Usuario', on_delete=models.CASCADE)
    #: proyecto del que participa el usuario
    proyecto = models.ForeignKey('administracion.Proyecto', on_delete=models.CASCADE)

templates/administracion/crearRol.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center pt-3 mb-3">Crear Rol</h1>
        <form class="pt-3" METHOD="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-12">
                    <label for="id_nombre">Nombre</label>
                    {{ form.nombre }}
                </div>
            </div>
            <div class="form-group row mt-3">
                <p class="col-sm-12">Permisos:</p>
                <div class="col-sm-12 col-md-6">
                    <div class="custom-control custom-checkbox">
                        <!--<input type="checkbox" class="custom-control-input" id="crearItem" name="crearItem">-->
                        {{ form.crear_item }}
                        <label class="custom-control-label" for="id_crear_item">Crear item</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.aprobar_item }}
                        <label class="custom-control-label" for="id_aprobar_item">Aprobar item</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.modificar_item }}
                        <label class="custom-control-label" for="id_modificar_item">Modificar item</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.reversionar_item }}
                        <label class="custom-control-label" for="id_reversionar_item">Reversionar item</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.desactivar_item }}
                        <label class="custom-control-label" for="id_desactivar_item">Desactivar item</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.crear_relaciones_ph }}
                        <label class="custom-control-label" for="id_crear_relaciones_ph">Crear relaciones padre-hijo</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.crear_relaciones_as }}
                        <label class="custom-control-label" for="id_crear_relaciones_as">Crear relaciones antecesor-sucesor</label>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="custom-control custom-checkbox">
                        {{ form.borrar_relaciones }}
                        <label class="custom-control-label" for="id_borrar_relaciones">Desactivar relaciones</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.ver_item }}
                        <label class="custom-control-label" for="id_ver_item">Ver Item</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.crear_linea_base }}
                        <label class="custom-control-label" for="id_crear_linea_base">Crear Línea Base</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.cerrar_fase }}
                        <label class="custom-control-label" for="id_cerrar_fase">Cerrar Fase</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.cerrar_proyecto }}
                        <label class="custom-control-label" for="id_cerrar_proyecto">Cerrar Proyecto</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.solicitar_ruptura_lb }}
                        <label class="custom-control-label" for="id_solicitar_ruptura_lb">Solicitar Ruptura de Línea Base</label>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center pt-3">
                <div class="col-md-3">
                    <button type="submit" class="btn btn-primary btn-block">Crear</button>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

templates/administracion/editarTipoItem.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center pt-3 mb-3">Editar tipo de item</h1>
        <form class="pt-3" METHOD="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-12 col-md-8">
                    <label for="id_nombre">Nombre</label>
                    {{ form.nombre }}
                </div>
                <div class="form-group col-sm-12 col-md-4">
                    <label for="id_prefijo">Prefijo</label>
                    {{ form.prefijo }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_descripcion">Descripcion</label>
                {{ form.descripcion }}
            </div>
            <div class="row">
                <div class="col-md-3">
                    <button type="submit" class="btn btn-primary btn-block">Confirmar cambios</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/administracion/verProyecto.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container h-100">
        <div class="shadow-lg p-3 mb-5 bg-white rounded mt-5">
            <h2 class="text-center pt-3 mb-3">{{ proyecto.nombre }}</h2>
                <table class="table">
                    <tbody>
                        <tr class="">
                            <td>Estado </td><td>{{estado}}</td>
                        </tr>
                        <tr class="">
                            <td>Fecha de Inicio </td><td>{{proyecto.fecha_inicio}}</td>
                        </tr>
                        {% if proyecto.fecha_ejecucion %}
                        <tr class="">
                            <td>Fecha de inicio de Ejecución </td><td>{{proyecto.fecha_ejecucion}}</td>
                        </tr>
                        {% endif %}
                        {% if proyecto.fecha_finalizado %}
                        <tr class="">
                            <td>Fecha de Finalización</td><td>{{proyecto.fecha_finalizado}}</td>
                        </tr>
                        {% endif %}
                        {% if proyecto.fecha_cancelado %}
                        <tr class="">
                            <td>Fecha de Cancelación </td><td>{{proyecto.fecha_cancelado}}</td>
                        </tr>
                        {% endif %}
                        <tr class="table">
                            <td>Gerente del Proyecto </td><td>{{gerente}}</td>
                        </tr>
                        <tr class="">
                            <td>Miembros del Comité</td>
                            <td>
                                <ul>
                                    {% for miembro in proyecto.comite.all %}
                                        <li>{{ miembro }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr><tr class="">
                            <td>Participantes</td>
                            <td>
                                <ul>
                                    {% for participante in proyecto.participantes.all %}
                                        <li>{{ participante }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr class="">
                            <td>Tipos de Item</td>
                            <td>
                                <ul>
                                    {% for tipoItem in tipo_item %}
                                        <li>{{ tipoItem.nombre }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr class="">
                            <td>Fases</td>
                            <td>
                                <ul>
                                    {% for fase in fases %}
                                        {% if fase.nombre == '' %}
                                            <li>Nombre Indefinido</li>
                                        {% else %}
                                            <li>{{ fase.nombre }}</li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mt-3 pb-3">
                {% if proyecto.estado != 'cancelado' %}
                    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        Acciones
                    </button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        {% if proyecto.estado == 'iniciado' %}
                                <a class="list-group-item dropdown-item"
                                   href="{% url 'administracion:tipoItemPorProyecto' proyecto.id %}" role="button">
                                    Administrar Tipo de Item
                                </a>
                            {% else %}
                                <a class="list-group-item dropdown-item disabled" role="button">
                                    Administrar Tipo de Item <h6 style="color: #f57900">(solo en estado iniciado)</h6>
                                </a>
                            {% endif %}
                            <a class="list-group-item dropdown-item"
                               href="{% url 'administracion:administrarParticipantes' proyecto.id %}" role="button">
                                Administrar Participantes
                            </a>
                            <a class="list-group-item dropdown-item {% if  proyecto.estado == 'finalizado' %}disabled{% endif %}"
                               href="{% url 'administracion:administrarComite' proyecto.id %}" role="button">
                                Administrar Miembros del Comité
                            </a>
                            <a class="list-group-item dropdown-item {% if  proyecto.estado == 'finalizado' %}disabled{% endif %}"
                               href="{% url 'administracion:editarProyecto' proyecto.id %}" role="button">
                                Modificar datos del Proyecto
                            </a>
                            <a class="list-group-item dropdown-item {% if  proyecto.estado == 'finalizado' %}disabled{% endif %}"
                               href="{% url 'administracion:administrarFasesProyecto' proyecto.id %}" role="button">
                                Administrar Fases del Proyecto
                            </a>
                            <a class="list-group-item dropdown-item"
                               href="{% url 'administracion:administrarRoles' proyecto.id %}" role="button">
                                Administrar roles
                            </a>
                    </div>
                    {% if proyecto.estado == 'iniciado' %}
                        <button
                            {% if habilitadofase == False or habilitadocomite == False or habilitadotipo == False %}
                                class="btn btn-secondary" onclick="show_alert('Debe definir {% if habilitadofase == False %}nombres de las fases{% endif %}{% if habilitadofase == False and habilitadocomite == False %}, {% endif %}{% if proyecto.comite.count < proyecto.cant_comite %}los miembros del comité {% endif %}{% if habilitadocomite == False and habilitadotipo == False %}y{% endif %} {% if habilitadotipo == False %}aunque sea {{ proyecto.numero_fases }} tipos de ítem{% endif %}')"
                            {% else %}
                                onclick="show_modal('{% url 'administracion:estadoProyecto2' proyecto.id 'en ejecucion' %}')" class="btn btn-primary"
                            {% endif %}
                        >Pasar a en ejecucion</button>
                        <button onclick="show_modal('{% url 'administracion:estadoProyecto2' proyecto.id 'cancelado' %}')" class="btn btn-danger">Pasar a cancelado</button>
                    {% elif proyecto.estado == 'en ejecucion' %}
                        <button onclick="show_modal('{% url 'administracion:estadoProyecto2' proyecto.id 'cancelado' %}')" class="btn btn-danger">Pasar a cancelado</button>
                    {% endif %}
                {% else %}
                    <div class="d-inline-block">
                        <h5 class="alert alert-warning">Proyecto Cancelado: No se permiten acciones</h5>
                    </div>
                {% endif %}

                <div class="float-right">
                    <button id="btnGroupDrop2" type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Auditoría del Proyecto
                    </button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
                        <a class="list-group-item dropdown-item" role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'proyecto' %}">Proyecto</a>
                        <a class="list-group-item dropdown-item" role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'tipoItem' %}">Tipos de Item</a>
                        <a class="list-group-item dropdown-item " role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'fase' %}">Fases</a>
                        <a class="list-group-item dropdown-item"role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'rol' %}">Roles</a>
                        <a class="list-group-item dropdown-item" role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'Lineas Base' %}">Líneas Base</a>
                        <a class="list-group-item dropdown-item"role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'Participante' %}">Participantes</a>
                        <a class="list-group-item dropdown-item"role="button"
                           href="{% url 'administracion:auditoriaParticular' proyecto.id 'Item' %}">Items</a>
                    </div>
                    <a class="btn btn-primary" href="{% url 'administracion:proyectos' 'todos'%}" role="button">
                        Volver a Lista de Proyectos
                    </a>
                </div>
                <div id="msj">

                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmacion" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Estas seguro de que desea cambiar el estado del proyecto?</h3>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <a class="btn btn-success" id="botonConfirmar" href="">Confirmar</a>
                    <button type="button" class="btn btn-danger float-right" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //var $ = jQuery.noConflict();
        function show_modal( url ){
            $('#botonConfirmar').attr('href',url)
            $('#confirmacion').modal('show');
        }
        function show_alert(msj) {
            document.querySelector('#msj').innerHTML=msj;
            document.querySelector('#msj').classList='alert alert-warning mt-3'
        }
    </script>
{% endblock %}