ItemManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('administracion/', include('administracion.urls')),
    path('desarrollo/', include('desarrollo.urls')),
    path('configuracion/', include('configuracion.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

desarrollo/urls.py
from django.urls import path

from desarrollo import views

app_name = 'desarrollo'
urlpatterns = [
    # URLs de Mati
    path('fase/<int:id_fase>/tipo/<int:id_tipo>/items/crear', views.crear_item, name='crearItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>', views.ver_item, name='verItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/historialversiones', views.historial_versiones_item,
         name='histVersionesItem'),
    path('proyectos/<int:id_proyecto>/aprobacion', views.menu_aprobacion, name='menuAprobacion'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/reversionar/<int:id_version_anterior>', views.reversionar_item,
         name='reversionarItem'),
    # path('items/<int:id_item>/calculo_impacto', views.calculo_de_impacto, name='calculoDeImpacto'),
    # URLs de David
    path('<str:filtro>', views.index, name='indexDesarrollo'),
    path('proyectos/<int:id_proyecto>/', views.ver_proyecto, name='verProyecto'),
    # URLs de Fer
    path('proyectos/<int:id_proyecto>/relacionar', views.relacionar_item, name='relacionar'),
    path('proyectos/<int:id_proyecto>/desactivar_relacion', views.desactivar_relacion_item, name='desactivarRelacion'),
    path('proyectos/<int:id_proyecto>/cerrar_fase', views.cerrar_fase, name='cerrarFase'),
    # URLs de Pao
    path('items/<int:id_item>/solicitar', views.solicitud_aprobacion, name='solicitarAprobacion'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/desactivar', views.desactivar_item, name='desactivarItem'),
    path('items/<int:id_item>/aprobar', views.aprobar_item, name='aprobarItem'),
    path('items/<int:id_item>/desaprobar', views.desaprobar_item, name='desaprobarItem'),
    path('proyectos/<int:id_proyecto>/items/<int:id_item>/editar', views.modificar_item, name='editarItem'),
    path('items/<int:id_item>/votar', views.votacion_item_en_revision_desarrollo, name='votacionItem'),
    path('items/<int:id_item>/votar2', views.votacion_item_en_revision_aprobado, name='votacionItem2'),
    path('items/<int:id_item>/votar3', views.votacion_item_en_revision_lineaBase, name='votacionItem3')
]

login/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.user_register, name='register'),

    path('admin/', views.admin, name='admin'),
    path('admin/access/', views.users_access, name='administrarAccesos'),
    path('<str:name>/update/', views.user_update, name='userUpdate'),
    path(
        'accesoDenegado/',
        TemplateView.as_view(template_name='login/accesoDenegado.html'),
        name='AccesoDenegado',
    ),

    # urls de Mati
    path('auditoria/<str:tipo>', views.auditoria, name='auditoria'),
]

desarrollo/models.py
"""
Mapeador objeto-relacional en el que es posible definir la estructura de la base de datos utilizando código Python.
"""
from django.db import models
from administracion.models import Fase
from django.utils.timezone import now


class Item(models.Model):
    """
    clase que representa a los ítems que son instanciados a partir de un tipo de ítem
    """
    #: nombre que identifica al ítem
    nombre = models.CharField(max_length=200, null=False)
    #: estado actual, puede tomar los valores: en desarrollo, pendiente de aprobación, aprobado, desactivado,
    # en revisión, en línea base
    estado = models.CharField(max_length=100, default='En Desarrollo', null=False)
    numeracion = models.IntegerField(default=1)
    #: version actual del ítem que va cambiando luego de cada nueva relación y cada modificación de sus datos
    version = models.PositiveIntegerField(null=False, default=1)
    #: valor que define el impacto del ítem en el proyecto. Toma valores enteros entre 1 y 10
    complejidad = models.PositiveIntegerField(default=5, null=False)
    #: comentarios opcionales para describir al ítem
    descripcion = models.CharField(max_length=200, null=True)
    #: tipo que tendrá el ítem, de eso dependen sus atributos particulares
    tipo_item = models.ForeignKey('administracion.TipoItem', on_delete=models.CASCADE)
    #: fase del proyecto en la que se crea el ítem
    fase = models.ForeignKey('administracion.Fase', on_delete=models.CASCADE, default=None, blank=True, null=True)
    #: versión anterior a la del item actual
    version_anterior = models.ForeignKey('desarrollo.Item', on_delete=models.CASCADE, default=None, null=True)
    #: id para identificar a todas las versiones de un mismo ítem
    id_version = models.IntegerField(null=True)

    # listas para las relaciones del ítem
    antecesores = models.ManyToManyField('Item', related_name='item_desarrollo_antecesores', blank=True)
    sucesores = models.ManyToManyField('Item', related_name='item_desarrollo_sucesores', blank=True)
    padres = models.ManyToManyField('Item', related_name='item_desarrollo_padres', blank=True)
    hijos = models.ManyToManyField('Item', related_name='item_desarrollo_hijos', blank=True)

    # constantes del modelo
    ESTADO_DESARROLLO = 'En Desarrollo'
    ESTADO_PENDIENTE = 'Pendiente de Aprobacion'
    ESTADO_APROBADO = 'Aprobado'
    ESTADO_REVISION = 'En Revision'
    ESTADO_LINEABASE = 'En Linea Base'
    ESTADO_DESACTIVADO = 'Desactivado'

    def __str__(self):
        return self.nombre

    def es_ultima_version(self):
        ultima_item_version = Item.objects.filter(id_version=self.id_version, estado__regex='^(?!' + Item.ESTADO_DESACTIVADO + ')'
                                   ).order_by('version').last()
        return ultima_item_version.version == self.version

    def get_ultima_version(self):
        return Item.objects.filter(id_version=self.id_version, estado__regex='^(?!' + Item.ESTADO_DESACTIVADO + ')'
                                   ).order_by('version').last()


class AtributoParticular(models.Model):
    """
    Esta clase representa cada uno de los atributos extra que tiene un ítem dependiendo de su tipo de ítem
    """
    #: item al cual pertenecen estos atributos
    item = models.ForeignKey('desarrollo.Item', on_delete=models.CASCADE, default=None)
    #: nombre del atributo
    nombre = models.CharField(max_length=200, null=False)
    #: tipo del atributo, puede tomar valores: text, numeric, file, date
    tipo = models.CharField(max_length=100, null=False)
    #: valor que es almacenado dentro del atributo
    valor = models.CharField(max_length=300)

    def __str__(self):
        return self.nombre


class HistoricalItem(models.Model):
    """
    Clase que sirve para guardar datos de auditoría para cada item del proyecto
    """
    #: usuario que participa en el proyecto
    item = models.ForeignKey('desarrollo.Item', on_delete=models.CASCADE)
    #: usuario que realizó la acción
    history_user = models.CharField(max_length=150, default='None')
    #: fecha y hora en la que se realizó la acción
    history_date = models.DateTimeField(default=now)
    #: razón de cambio (nulo por defecto)
    history_change_reason = models.CharField(max_length=200, null=True)
    #: tipo de cambio: puede ser crear, modificar, eliminar, reversionar, cambiar estado, relacionar, desrelacionar
    history_type = models.CharField(max_length=250)
    # constantes
    TIPO_CREAR = '+'
    TIPO_MODIFICAR = '~'
    TIPO_ELIMINAR = '-'
    TIPO_REVERSIONAR = 'reversión'
    TIPO_ESTADO = 'estado cambiado a '
    TIPO_RELACIONAR = 'relación creada'
    TIPO_DESRELACIONAR = 'relación eliminada'

desarrollo/forms.py
"""
Formularios para la aplicacion administración
"""
from django import forms
from desarrollo.models import Item


class ItemForm(forms.ModelForm):
    """
    Formulario para la creación de ítems
    """

    class Meta:
        model = Item
        fields = ('nombre', 'complejidad', 'descripcion')
        help_texts = {
            'complejidad': 'número entero entre 1 y 10',
        }

    def __init__(self, *args, **kwargs):
        """
        Añadimos al constructor de la clase las restricciones de que el campo complejidad solo pueda tomar valores
        entre 1 y 10 y modificamos el campo descripcion para que no sea requerido
        """
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['complejidad'].widget.attrs['min'] = 1
        self.fields['complejidad'].widget.attrs['max'] = 10
        self.fields['descripcion'].required = False

    def clean_complejidad(self):
        """
        modificamos clean_data de complejidad para que controle que el valor esté entre 1 y 10

        :return: retornará el valor de complejidad o alzará un error de validacion
        """
        complejidad = self.cleaned_data['complejidad']
        if complejidad > 10 or complejidad < 1:
            raise forms.ValidationError('Tiene que estar en el rango de [1,10].')
        return complejidad


class EditarItemForm(forms.Form):
    """Formulario para la modificar Items"""

    nombre = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                          'value': 'Item'}))
    complejidad = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class': 'numberinput form-control',
                                                                                  'type': 'number',
                                                                                  'min': '1', 'max': '10',
                                                                                  'value': '5'}))
    descripcion = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3',
                                                                              'value': ''}))

    def __init__(self, *args, **kwargs):
        super(EditarItemForm, self).__init__(*args, **kwargs)

templates/desarrollo/item_adjuntar_archivo.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center pt-3 pb-3">Adjuntar archivos</h2>
        <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </div>
{% endblock %}

templates/desarrollo/item_menu_aprobacion.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-8 ">
                <h3 class="text-center mt-3 mb-5">Menú de Aprobación </h3>
                <table class="table table-active">
                    <thead class="thead-light">
                        <tr>
                            {% for fase in lista_fases %}
                                <th class="">Fase: {{ fase.nombre }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="">
                            {% if not lista_fases %}
                                <div class="alert alert-warning">Su usuario no posee permisos de aprobación para ninguna fase de este proyecto.</div>
                            {% endif %}
                            {% for fase in lista_fases %}
                                <td class="justify-content-center">
                                    <div class="list-group pt-2">
                                        <ul>
                                            {% for item in lista_items %}
                                                {% if item.fase == fase %}
                                                    {% if item.estado == estado %}
                                                        <li class="list-group">
                                                            <a class="align-baseline" href="{% url 'desarrollo:verItem' proyecto.id item.id %}" >
                                                               {{ item.tipo_item.prefijo }}_{{ item.nombre }}
                                                            </a>

                                                            {% if item.antecesores.count != 0 or  item.padres.count != 0 or item.fase.id == primera_fase.id %}
                                                            <a class="btn btn-success" href="{% url 'desarrollo:aprobarItem' item.id %}" >
                                                               Aprobar
                                                            </a>
                                                                {% else %}
                                                                <button type="button" class="btn btn-secondary"
                                                                        data-toggle="modal" data-target="#myModal">
                                                                    Aprobar
                                                                    </button>

                                                                <div id="myModal" class="modal fade" role="dialog">
                                                                    <div class="modal-dialog">
                                                                        <div class="modal-content">
                                                                            <div class="modal-header ">
                                                                                <h4 class="modal-title font-weight-bold">
                                                                                    No puede aprobarse este item
                                                                                </h4>
                                                                            </div>
                                                                            <div class="modal-body">
                                                                                <p>El item no posee padres ni antecesores.
                                                                                </p>
                                                                            </div>
                                                                            <div class="modal-footer">
                                                                                <button type="button" class="btn btn-info"
                                                                                    data-dismiss="modal">
                                                                                    Cerrar
                                                                                </button>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                {% endif %}
                                                            <a class="btn btn-danger mt-2" href="{% url 'desarrollo:desaprobarItem' item.id %}" >
                                                               Desaprobar
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>

                <div class="col-sm-12 mt-4">
                    <a href="{% url 'desarrollo:verProyecto' proyecto.id %}" class="btn btn-primary float-right">Volver atrás</a>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

templates/desarrollo/item_ver.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-8 ">
                <h3 class="text-center mt-3 mb-5">{{item.tipo_item.prefijo}}_{{item.nombre}} </h3>
                <table class="table">
                    <tbody>
                        <tr class="">
                            <th rowspan="5" class="text-center align-middle h5">Item</th>
                        </tr>
                        <tr>
                            <td>Tipo de item</td>
                            <td>{{ item.tipo_item.nombre }}</td>
                        </tr>
                        <tr>
                            <td>Estado</td>
                            {% if  item.estado == item.ESTADO_LINEABASE%}
                            <td class="text-dark font-weight-bold">{{ item.estado }}</td>
                                {% elif item.estado == item.ESTADO_APROBADO %}
                                <td class="text-success font-weight-bold">{{ item.estado }}</td>
                                {% elif item.estado == item.ESTADO_PENDIENTE %}
                                <td class="text-warning font-weight-bold">{{ item.estado }}</td>
                                {% elif item.estado == item.ESTADO_DESARROLLO %}
                                <td class="text-danger font-weight-bold">{{ item.estado }}</td>
                                {% elif item.estado == item.ESTADO_REVISION %}
                                <td class="text-info font-weight-bold">{{ item.estado }}</td>
                                {% elif item.estado == item.ESTADO_DESACTIVADO %}
                                <td class="text-muted font-weight-bold">
                                    {% if es_vers_actual %}
                                        {{ item.estado }}
                                    {% else %}
                                        Versión Anterior
                                    {% endif %}
                                </td>
                            {% endif %}
                        </tr>
                        <tr>

                            <td>Proyecto</td>
                            <td>{{ proyecto.nombre }}</td>
                        </tr>
                        <tr>
                            <td>Fase</td>
                            <td>{{ fase.nombre }}</td>
                        </tr>

                        <tr>
                            <th rowspan="5" class="text-center align-middle h5">Atributos Comunes</th>
                        </tr>
                        <tr>
                            <td>Nombre</td>
                            <td>{{ item.nombre }}</td>
                        </tr>
                        <tr>
                            <td>Complejidad</td>
                            <td>{{ item.complejidad }}
                                <a class="btn btn-outline-primary" data-toggle="modal" data-target="#myModal">
                                    Cálculo de Impacto
                                </a>
                                <!-- Modal -->
                                <div id="myModal" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                    <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Resultado del Cálculo</h4>
                                                <a class="close btn-outline-danger" data-dismiss="modal">&times;</a>
                                            </div>
                                            <div class="modal-body" style="overflow-x: auto;">
                                                <h5 class="text-info m-3 font-weight-bold" align="middle">
                                                    El Cálculo de Impacto para el item "{{ item.nombre }}" genera un resultado igual a:
                                                </h5>
                                                <div class="alert alert-warning m-3">
                                                    <h5 align="middle">
                                                        {{ impacto }}
                                                    </h5>
                                                </div>
                                                <div class="table center">
                                                    <table>
                                                        <thead>
                                                        {% for fase in lista_fases_impacto %}
                                                             <th>{{ fase.nombre }}</th>
                                                        {% endfor %}
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                {% for fase in lista_fases_impacto %}
                                                                    <td>
                                                                        {% for sumando in lista_impacto %}
                                                                            {% if sumando.fase == fase %}
                                                                                {{ sumando.nombre }}({{ sumando.complejidad }})<hr>
                                                                            {% endif %}
                                                                        {% endfor %}
                                                                    </td>
                                                                {% endfor %}
                                                            </tr>
                                                      </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Cerrar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>Version</td>
                            <td>{{ item.version }}
                                <a class="btn btn-outline-primary" href="{% url 'desarrollo:histVersionesItem' proyecto.id item.id %}" >historial de versiones</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Descripcion</td>
                            <td>{{ item.descripcion }}</td>
                        </tr>
                        {% if lista_atributos %}
                            <tr>
                                <th rowspan="{{lista_atributos.count|add:1}}" class="text-center align-middle h5">Atributos particulares</th>
                            </tr>
                            {% for atributo in lista_atributos %}
                                <tr>
                                    <td>{{ atributo.nombre }}</td>
                                    <td>
                                        {% if atributo.tipo == 'file' %}
                                            {% if not atributo.valor %}
                                                <a href="#" class="btn disabled">Archivo (vacio)</a>
                                                {% else %}
                                                <a href="{{ atributo.valor }}" target="_blank" >Archivo</a>
                                                {% endif %}
                                        {% else %}
                                            {{ atributo.valor }}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
                <hr>
                <div class="col-sm-12 mt-4">
                    <a href="{% url 'desarrollo:verProyecto' proyecto.id %}" class="btn btn-primary float-right">Volver atrás</a>
                </div>
                {% if item.estado == desarrollo %}
                    <a class="btn btn-info" href="{% url 'desarrollo:editarItem' proyecto.id item.id%}">Editar</a>

                    <a class="btn btn-success" href="{% url 'desarrollo:solicitarAprobacion' item.id %}" >Solicitar Aprobación</a>
                    {% if item.antecesores.count != 0 or item.padres.count != 0 %}
                        <button type="button" class="btn btn-secondary" onclick="showAlert()">Desactivar Ítem</button>
                    {% else %}
                        <a class="btn btn-danger" href="{% url 'desarrollo:desactivarItem' proyecto.id item.id %}">Desactivar Ítem</a>
                    {% endif %}

                {% endif %}

                {% if item.estado == 'En Revision' %}
                    <a class="btn btn-primary" href="{% url 'desarrollo:votacionItem' item.id %}" >En Desarrollo</a>
                    <a class="btn btn-info" href="{% url 'desarrollo:votacionItem2' item.id %}">Aprobar</a>
                {% endif %}

            </div>
            <div class="mt-4 alert alert-warning" id="alertarelaciones" style="visibility: hidden;">
                No se puede desactivar por que es antecesor/padre de otros items
            </div>
        </div>

    </div>
    <script>
        const showAlert = ()=>{
            const alertDiv = document.getElementById('alertarelaciones');
            alertDiv.style.visibility = 'visible';
        }
    </script>
{% endblock %}

templates/desarrollo/proyecto_ver_unico.html
{% extends 'login/loginHeader.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center pt-3 mb-5">{{ proyecto.nombre }}</h1>
        <div class="btn float-right">
            <a class="btn btn-info" href="{% url 'desarrollo:menuAprobacion' proyecto.id %}"
               {% if es_aprobador == False %}disabled=""{% endif %} style="color: white">Aprobar items</a>
            <a class="btn btn-info"
               href="{% url 'desarrollo:relacionar' proyecto.id %}"
               style="color: white">
                Relacionar Items
            </a>
            <a class="btn btn-info"
               href="{% url 'desarrollo:desactivarRelacion' proyecto.id %}"
               style="color: white">
                Desactivar relaciones entre items
            </a>
            <a class="btn btn-info"
               href="{% url 'desarrollo:cerrarFase' proyecto.id %}"
               style="color: white">
                Cerrar Fase
            </a>
        </div>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    {% for fase in proyecto.fase_set.all %}
                        <th class="">{{ fase.nombre }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr class="">
                    {% for fase in proyecto.fase_set.all %}
                        <td class="justify-content-center">
                            <div class="dropdown">
                                <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Asignar item
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#" style="color: #4e555b">
                                        (seleccione tipo)
                                    </a>
                                    {% for tipoitem in proyecto.tipoitem_set.all %}
                                        {% if tipoitem in fase.tipos_item.all %}
                                            <a class="dropdown-item {% if proyecto.estado != estado %}disabled{% endif %}" role="button"
                                               href="{% url 'desarrollo:crearItem' fase.id tipoitem.id %}"  >
                                                {{ tipoitem.nombre }}</a>
                                        {% endif %}
                                    {% endfor %}
                                    {% for tipo in lista_tipos %}
                                        <a class="dropdown-item {% if proyecto.estado != estado %}disabled{% endif %}" href="{% url 'desarrollo:crearItem' fase.id tipo.id %}"
                                           role="button">
                                            {{ tipo.nombre }}
                                        </a>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="list-group pt-2">
                                <ul>
                                    {% for item in lista_items %}
                                        {% if item.fase == fase and item.estado != desactivado %}
                                            <li class="list-group">
                                                <a class="align-baseline"
                                                   href="{% url 'desarrollo:verItem' proyecto.id item.id %}" >
                                                   {{ item.tipo_item.prefijo }} {% if item.numeracion < 10 %}0{% endif %}{{ item.numeracion    }}-{{ item.nombre }}
                                                </a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>

        <div class="col-sm-12 mt-4">
            <a href="{% url 'desarrollo:indexDesarrollo' 'todos' %}" class="btn btn-primary float-right">Volver atrás</a>
        </div>
    </div>
{% endblock %}